"""Tests for audit endpoints."""

from fastapi.testclient import TestClient


def test_list_audit_logs(client: TestClient, admin_token: str) -> None:
    """Admin can list audit logs."""
    response = client.get(
        "/api/v1/audit",
        headers={"Authorization": f"Bearer {admin_token}"},
    )
    assert response.status_code == 200
    data = response.json()
    assert "items" in data

    # We should have audit logs generated by earlier tests (e.g. creating users/policies)
    assert len(data["items"]) >= 1


def test_list_audit_logs_as_viewer_fails(client: TestClient, viewer_token: str) -> None:
    """Viewer cannot list audit logs."""
    response = client.get(
        "/api/v1/audit",
        headers={"Authorization": f"Bearer {viewer_token}"},
    )
    assert response.status_code == 403
